export const VENDOR_REJECTION_REASON_MIN_LENGTH = 10;
export const VENDOR_REJECTION_REASON_MAX_LENGTH = 500;
export const VENDOR_REJECTION_REASON_LENGTH_MESSAGE = `Informe um motivo entre ${VENDOR_REJECTION_REASON_MIN_LENGTH} e ${VENDOR_REJECTION_REASON_MAX_LENGTH} caracteres.`;
