import type { ProductGridItem } from "./product-grid-card";

/**
 * Lista de produtos mockados para a página de produtos.
 *
 * TODO: Substituir por requisição ao backend — GET /api/products
 * Os dados mockados abaixo devem ser carregados dinamicamente via API/GraphQL.
 */
export const PRODUCTS_LIST: ProductGridItem[] = [
  {
    id: "prod-1",
    category: "Piteira",
    name: "Piteira Tradicional",
    badge: "Essencial",
    originalPrice: 8.9,
    price: 6.9,
    rating: 4.4,
    reviews: 678,
    image: "/images/products/Image (Piteira Tradicional).png",
  },
  {
    id: "prod-2",
    category: "Seda",
    name: "Tradicional Slim",
    badge: "Clássico",
    originalPrice: 11.9,
    price: 8.9,
    rating: 4.5,
    reviews: 521,
    image: "/images/products/Image (Tradicional Slim).png",
  },
  {
    id: "prod-3",
    category: "Seda",
    name: "Hemp King Size",
    badge: "Orgânico",
    originalPrice: 18.9,
    price: 14.9,
    rating: 4.9,
    reviews: 312,
    image: "/images/products/Image (Hemp King Size).png",
  },
  {
    id: "prod-4",
    category: "Seda",
    name: "Alfafa King Size",
    badge: "Mais Vendido",
    originalPrice: 16.9,
    price: 12.9,
    rating: 4.8,
    reviews: 334,
    image: "/images/products/Image (Alfafa King Size).png",
  },
  {
    id: "prod-5",
    category: "Seda",
    name: "Insane Brown",
    badge: "Premium",
    originalPrice: 19.9,
    price: 15.9,
    rating: 4.6,
    reviews: 203,
    image: "/images/products/Image (Insane Brown).png",
  },
  {
    id: "prod-6",
    category: "Seda",
    name: "Brown King Size",
    badge: "Novo",
    originalPrice: 14.9,
    price: 11.9,
    rating: 3.7,
    reviews: 288,
    image: "/images/products/Image (Brown King Size).png",
  },
  {
    id: "prod-7",
    category: "Seda",
    name: "Pink Queen Size",
    badge: "Especial",
    originalPrice: 17.9,
    price: 13.9,
    rating: 4.8,
    reviews: 156,
    image: "/images/products/Image (Pink Queen Size).png",
  },
  {
    id: "prod-8",
    category: "Seda",
    name: "Livreto Hemp",
    badge: "Natural",
    originalPrice: 21.9,
    price: 16.9,
    rating: 4.7,
    reviews: 145,
    image: "/images/products/Image (Hemp King Size).png",
  },
  {
    id: "prod-9",
    category: "Acessório",
    name: "Bag Tradicional",
    badge: "Kit",
    originalPrice: 24.9,
    price: 19.9,
    rating: 4.9,
    reviews: 98,
    image: "/images/products/Image (Bag Tradicional).png",
  },
];
